### PR TITLE
Feature/swift 3

### PR DESCRIPTION
**Pull request by willk37**
Our file directory structure is a little different from what the upstream/master is using so I just pulled in the upstream/master changes and then moved things around to match our directory structure.

### CODE REVIEW

**Comment by ChadEBrady** [comment]
This looks good, the thing I was worried about happened though.  If you look at the current issues in the upstream/master, there is a swift 3 bug that's going to hurt us because the backend uses a different decoder 😞 So we won't be able to go live with this until that's fixed, or we might have to figure out how to fix it ourselves.

**Review by ChadEBrady — APPROVED** [review]

**Comment by dmauro** [comment]
Sorry, what's the thing that happened exactly, Chad?

**Comment by ChadEBrady** [comment]
https://github.com/malczak/hashids/issues

**Comment by ChadEBrady** [comment]
Swift 3 conversion is really tricky on this file. I've played with for a while when swift 3 first came out and couldn't get it in my given time, and apparently it's broken

**Comment by dmauro** [comment]
Are we sure this will be a problem for us? It sounds like it works with php at least.

**Comment by ChadEBrady** [comment]
We'll have to check with what the pound folk are using on the backend. Php or python

**Comment by dmauro** [comment]
Can we just use the objective-C version?

**Comment by ChadEBrady** [comment]
😱 @dmauro how dare you...

**Comment by ChadEBrady** [comment]
yeah probably

**Comment by dmauro** [comment]
Is there a way for us to easily double check the validity of how this hashes? If not, we should probably switch to Objective-C. And you know how much I am loathe to say that :)

**Comment by ChadEBrady** [comment]
I think tenderizer has tests to verify

**Comment by ChadEBrady** [comment]
Yeah looks like Tenderizer does so that's good :)

**Comment by willk37** [comment]
There is already a unit test that validates against hashids generated with a php implementation. We could add a test with hashids generated by however the backend is doing it.

**Comment by willk37** [comment]
Also, the fact that php test passes makes me wonder if this is even a valid issue or a reporter error.

**Comment by ChadEBrady** [comment]
true, my concern has been quelled with the tenderizer test that I checked existed, I'm less concerned now 😄

**Comment by dmauro** [comment]
🎉

**Review by dmauro — APPROVED** [review]

**Comment by willk37** [comment]
So we're cool with just merging this?

**Comment by ChadEBrady** [comment]
I'm cool with it

**Comment by willk37** [comment]
I spent some more time looking into it and I was able to create a test that passes in the the Obj-C project and the Swift 2.3 branch but fails on the master branch (Swift 3). I'm going to leave a comment on that issue and hopefully it gets resolved somewhat quickly.

**Pull request closed without merging**
